name: Release

on:
  push:
    tags:
      - "*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Print version info
        id: semver
        run: |
          make version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        env:
          APPSCODE_ENV: prod
        run: |
          make release COMPRESS=yes

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/nats-logger-darwin-amd64.tar.gz
            bin/nats-logger-darwin-arm64.tar.gz
            bin/nats-logger-linux-amd64.tar.gz
            bin/nats-logger-linux-arm.tar.gz
            bin/nats-logger-linux-arm64.tar.gz
            bin/nats-logger-windows-amd64.zip
            bin/nats-logger-checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
